### ISSUE TITLE
Some package version conflicts

### ISSUE THREAD

**Issue by guanjiayi** [dmksjfl/MCQ#1]
The list of dependent packages you provided does not provide a version number, which leads to the direct installation of the latest package and some conflicts of dependent packages. For example, installing the latest tianshou package conflicts with the required gym<=0.18.3. Could you please provide a requirement file for reference?

**Comment by dmksjfl** [comment]
Hi Jiayi,

I have checked that we use tianshou==0.4.2 in our experiments. I will include a requirement.txt in this repo as soon as I can. Thanks for pointing out that!

**Comment by guanjiayi** [comment]
Hi Jiafei
Thank you very much for your reply, the problem has been solved.
