### ISSUE TITLE
Where to adjust N (the hyperparameter in Figure 2 of the paper)

### ISSUE THREAD

**Issue by daihuiao** [dmksjfl/MCQ#2]
如题

**Comment by dmksjfl** [comment]
In our paper, $N$ refers to the number of sampled actions (default is 10). It can be modified in this line:
https://github.com/dmksjfl/MCQ/blob/e596153c1170e632de4ea55678a4f63c22b594ef/offlinerl/config/algo/MCQ_config.py#L36

**Comment by daihuiao** [comment]
thank you for your reply
